### ISSUE TITLE
Clipper can shoot ground units

### ISSUE THREAD

**Issue by LeonariX58** [AeronGreva/AeroMindustry#11]
So, I was playing with the mod, when I realized that clippers bullets can hit ground blocks/units, with a processor, you can make them
work like a ground turret

![image](https://user-images.githubusercontent.com/75447012/171739966-474310a9-1249-42af-9403-97df0f5adecf.png)

**Comment by AeronGreva** [comment]
I just pushed a fix for the issue. Thank you for making me aware of it!
