### ISSUE TITLE
Change the mindustry logo

### ISSUE THREAD

**Issue by feu-follet** [AeronGreva/AeroMindustry#3]
Your mod should change the vanilla logo. Put for example the image there is on Github. To change the logo you must do that :
AeroMindustry / Sprites-override / ui / logo.png

**Comment by AeronGreva** [comment]
The mod's not quite big enough, in my opinion, to override the logo. Maybe once more content is introduced, I'll consider it.
Thanks for letting me know how, though. I appreciate it!
